![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [20]:
!pip install numpy



[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np
np.__version__

'2.2.3'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
array_2= np.array([[True,True,True],[True,True,True],[True,True,True]])
array_2
ejer_3 = np.full((3,3),True)
ejer_3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [4]:

for i in my_array:
    if i%2 == 1:
        print(i)
        
    

1
3
5
7
9


In [5]:
lista_impares  = []
lista_impares = [x for x in my_array if x%2 == 1]
print(lista_impares)

[np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)]


In [6]:
my_array %2 == 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [7]:
mask = my_array %2 == 1
my_array [mask]

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [8]:
my_array_solucion = my_array
for i,x in enumerate(my_array):
    if x%2 != 0:
        print(x)
        my_array_solucion[i] = -1
my_array_solucion
        

1
3
5
7
9


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
my_array [mask]= -1
my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [10]:
my_array = np.arange(10)
nuevo_array = np.where(my_array%2 != 0, -1,my_array) 
nuevo_array 

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [11]:
array_dimensiones = np.reshape(my_array,(2,5))
array_dimensiones

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [12]:
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)
c = np.concatenate((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [13]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate((a,b), axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print(c)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [15]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [16]:
my_array = np.arange(0,10)
my_array10 = my_array *10
print(my_array10)
print(my_array[0])
print(my_array[-1])
print(*my_array[1:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
9
1 2 3 4 5 6 7


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [17]:
my_matrix = np.array([[1,2,3],[1,2,3],[1,2,3]])
my_matrix_2 = np.arange(1,10).reshape(3,3)
my_matrix_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [18]:
secuencia = np.arange(1,50,3)
secuencia

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [19]:
secuencia_2 = np.arange(4,1,-.25)
secuencia_2

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

In [22]:
!pip install matplotlib

     ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
     - -------------------------------------- 0.2/8.1 MB 7.3 MB/s eta 0:00:02
     --- ------------------------------------ 0.7/8.1 MB 8.9 MB/s eta 0:00:01
     ----- ---------------------------------- 1.1/8.1 MB 8.7 MB/s eta 0:00:01
     -------- ------------------------------- 1.6/8.1 MB 9.4 MB/s eta 0:00:01
     ---------- ----------------------------- 2.2/8.1 MB 10.0 MB/s eta 0:00:01
     ------------- -------------------------- 2.7/8.1 MB 10.0 MB/s eta 0:00:01
     --------------- ------------------------ 3.1/8.1 MB 9.9 MB/s eta 0:00:01
     ------------------ --------------------- 3.6/8.1 MB 10.1 MB/s eta 0:00:01
     -------------------- ------------------- 4.1/8.1 MB 10.2 MB/s eta 0:00:01
     ---------------------- ----------------- 4.5/8.1 MB 10.4 MB/s eta 0:00:01
     ------------------------ --------------- 4.9/8.1 MB 10.2 MB/s eta 0:00:01
     -------------------------- ------------- 5.4/8.1 MB 10.1 MB/


[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [37]:

from PIL import Image
import matplotlib.pyplot as plt
imagen = Image.open("C:\\Users\\rafac\\REPO_PRUEBA\\ONLINE_DS_THEBRIDGE_RAFACERCOS\\MIS_EJERCICIOS\\numpy.png")
imagen = np.array(imagen)
imagen

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], shape=(306, 765, 4), dtype=uint8)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [24]:
my_array = np.arange(4).reshape(4,1)
print(my_array)
my_array.reshape(2,2)

[[0]
 [1]
 [2]
 [3]]


array([[0, 1],
       [2, 3]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [26]:
secuencia = np.random.randint(10,size = (4,5,3))
print(secuencia)

[[[0 8 8]
  [4 3 1]
  [6 5 2]
  [6 0 7]
  [2 4 9]]

 [[2 5 6]
  [6 5 7]
  [5 9 7]
  [4 1 6]
  [1 5 0]]

 [[8 7 2]
  [3 7 1]
  [0 0 6]
  [3 2 9]
  [0 1 1]]

 [[3 2 8]
  [0 7 2]
  [9 3 9]
  [6 1 0]
  [3 8 5]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [32]:
matriz = np.full((10,1),False)
print(matriz)
matriz.reshape((2,5))

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [42]:
x = np.random.randint(10, 20, size = (5,2,6))
print(np.size(x))
print(np.ndim(x))
print(x.shape[0])
print(x.shape[1])
print(x.shape[2])




60
3
5
2
6
