![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
my_array = np.arange(10)
print(*my_array[::-2])

9 7 5 3 1


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(*my_array[-2:-4:-1])


8 7


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(*my_array[2::-1])

2 1 0


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
matriz = np.arange(1,21).reshape((4,5))
print(matriz)
matriz_invertida = matriz [::-1,::-1]
print(matriz_invertida)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [8]:
matriz_transpuesta = matriz.T
matriz_transpuesta

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [43]:
matriz = np.arange(1,21).reshape((4,5))
matriz_resultado = matriz [:2:,:2:]
matriz_resultado

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [44]:
matriz = np.arange(1,21).reshape((4,5))
matriz_resultado = matriz [::2,::2]
matriz_resultado

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [50]:
matriz = np.arange(1,21).reshape((4,5))
matriz_resultado = matriz[:3:,::-1]
matriz_resultado

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [51]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mask = x != "Loro"
x[mask]

array(['Perro', 'Gato', 'Perro'], dtype='<U5')

In [53]:
lista_vacia = []
for i in x:
    if i != "Loro":
        lista_vacia.append(i)
print(*lista_vacia)


Perro Gato Perro


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [54]:
my_array = np.random.randint(20,size = (2,5,2))
my_array

array([[[ 8,  4],
        [ 0,  7],
        [12,  1],
        [18, 11],
        [14,  5]],

       [[ 2,  2],
        [12, 14],
        [11, 18],
        [18, 17],
        [ 1,  9]]], dtype=int32)

In [55]:
my_array = np.arange(20).reshape((2,5,2))
my_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [64]:
my_array = np.zeros(10)
print(my_array.nbytes)
my_array[3]=1
print(*my_array)

80
0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0


In [15]:
my_array = np.full(10, 0, dtype=np.int8)
print(my_array.nbytes)
my_array[3]=1
print(*my_array)

10
0 0 0 1 0 0 0 0 0 0


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [62]:
vector = np.arange(50,9,-1)
print(*vector)

50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [16]:
vector = np.array([1,2,0,0,4,0])
solucion = np.where(vector != 0)[0] #Cuando solo lleva la condicion como argumento np.where no transforma,
                                  #devuelve el indice de los casos verdaderos
solucion




array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [94]:
matriz = np.random.rand(10,10)
print(matriz.min())
print(matriz.max())

0.0033352014280123576
0.9914487818747043


In [20]:
matriz = np.random.randint(100,size = (10,10))
print(matriz)
print(np.min(matriz),"\n",np.max(matriz))

[[32 22 96 82 15 23 99 81 91 25]
 [38 46 95 50 94 94  1 16 14 49]
 [54 51 47 82 55 90 91 48 67 26]
 [53  8 71 22 34 89 23 32  0 57]
 [81  0  6 95  7 41 15 35  5 14]
 [43 19 29 60 46  9 44 73 99 95]
 [92 14  1 13 46 80 70 81 53 79]
 [88 83 62 41 33 58 31 59 11 24]
 [88 24 75 76 20 17 45 21 44 54]
 [25 79  0 61  3 18 62 91 41 81]]
0 
 99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [23]:

vector = np.random.randint(100,size =(30))
print(vector)
np.mean(vector)


[37 34 93 12 58 57 72 76 90 62  9 64 51 38 73 51 39 42 96 34 11 11  2 63
 88 81 98 54 58 81]


np.float64(54.5)

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [105]:
my_array = np.ones((4,4))
my_array[1:3:,1:3:] = 0
my_array


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [112]:
matriz = np.ones((8,8))
matriz [::2,::2] = 0
matriz [1::2,1::2] = 0
matriz

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [117]:
my_array = np.array([[0,1],[1,0]])
np.reshape(my_array,(2,2))
        
nuevo_array = np.tile(my_array,(4,4))
nuevo_array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [119]:
matriz_aleatoria = np.random.randint(100,size =(5,5))
print(matriz_aleatoria)
resultado = (matriz_aleatoria - np.mean(matriz_aleatoria))/ np.std(matriz_aleatoria)
print(resultado)

[[30 40 24 26 19]
 [50 16 40  6 39]
 [88 90 26  2 60]
 [70 62 16 66 41]
 [67 93 89 16 95]]
[[-0.58555076 -0.23783653 -0.79417929 -0.72463645 -0.96803641]
 [ 0.1098777  -1.07235067 -0.23783653 -1.4200649  -0.27260795]
 [ 1.43119176  1.5007346  -0.72463645 -1.55915059  0.45759192]
 [ 0.80530615  0.52713477 -1.07235067  0.66622046 -0.20306511]
 [ 0.70099188  1.60504887  1.46596318 -1.07235067  1.67459171]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [128]:
my_array = np.arange(11)
nuevo_array = np.where((my_array>=3) & (my_array<=8),-1,my_array)
print(nuevo_array)
mask = nuevo_array != -1
array_final= nuevo_array[mask]
print(array_final)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2  9 10]
